### ISSUE TITLE
Doesn't work with latest version of VScode

### ISSUE THREAD

**Issue by Izikiel** [13xforever/x86-assembly-textmate-bundle#5]

**Comment by 13xforever** [comment]
Can't confirm. More information needed.
What version of VS Code? What OS are you on? What doesn't work specifically? Have you tried to uninstall and reinstall extension again?

**Comment by 13xforever** [comment]
![asm_vsc_1 6 0](https://cloud.githubusercontent.com/assets/36445/19300359/4f3a3e7e-9073-11e6-9d42-4dc7d6269439.png)
![asm_atom_1 11 1](https://cloud.githubusercontent.com/assets/36445/19300363/5288cffa-9073-11e6-9d20-26df05bc871f.png)
![asm_st3_3126](https://cloud.githubusercontent.com/assets/36445/19300365/54d8cef4-9073-11e6-8840-14514ba21ba5.png)

**Comment by 13xforever** [comment]
Linux version seem to be fine as well (atom packages are still pending update):
![VS Code 1.6.0 on Linux](https://cloud.githubusercontent.com/assets/36445/19302792/9b5b6c92-9087-11e6-83c1-aa8317e39bd5.png)
![Atom 1.10.2 on Linux](https://cloud.githubusercontent.com/assets/36445/19302987/94ada71a-9088-11e6-87a3-6af8f66460fa.png)
![Sublime Text 3 on Linux](https://cloud.githubusercontent.com/assets/36445/19302931/543c816a-9088-11e6-82ac-53d73c3b0d36.png)

**Comment by 13xforever** [comment]
I can't test on MacOS, but I highly doubt there's any problem either, at least not with this extension.

**Comment by 13xforever** [comment]
Did a bit more testing. Looks like it's a bug/"feature" of vs code 1.6.0:

	Error: Couldn't find a compatible version of x86 and x86_64 Assembly with this version of Code.,
	   at e.getLastValidExtensionVersionReccursively (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:9:21334),
	   at /opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:9:21725,
	   at Object.m [as _notify] (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:5:23338),
	   at Object.enter (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:5:26916),
	   at _run (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:5:28744),
	   at _completed (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:5:28185),
	   at Object.m [as _notify] (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:5:23338),
	   at Object.enter (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:5:26916),
	   at _run (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:5:28744),
	   at _completed (/opt/visual-studio-code/resources/app/out/vs/code/node/sharedProcessMain.js:5:28185)",
	   source: file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js (93)

**Comment by 13xforever** [comment]
Did a workaround, version 2.2.7 should install again in VS Code 1.6.0

**Comment by Izikiel** [comment]
Sorry I didn't answer earlier, I was afk.
Yes, it was the linux version on vscode 1.6, now it's working, thanks!
